Add Chinese translations
workshopper/how-to-markdown pull request #42
Opened 2017-01-24 08:21 UTC by wangding

2017-01-24 12:17 UTC, denysdovhan requested changes

2017-01-24 12:17 UTC, denysdovhan commented on package.json
> +  "version": "1.2.2",
Do not modify version. I'll do it by myself.

2017-01-24 12:17 UTC, denysdovhan commented on package.json
> +    "王顶 <408542507@qq.com> (https://github.com/wangding)"
Please, use Latin characters in `package.json`

2017-01-24 12:17 UTC, denysdovhan commented on exercises/blockquotes/solution/zh-cn.md
> +# 好棒！
Please, find someone who can check and verify your translation.

2017-01-24 12:54 UTC, wangding commented on package.json
> +  "version": "1.2.2",
ok

2017-01-24 12:54 UTC, wangding commented on package.json
> +    "王顶 <408542507@qq.com> (https://github.com/wangding)"
ok

2017-01-24 12:55 UTC, wangding commented on exercises/blockquotes/solution/zh-cn.md
> +# 好棒！
ok

2017-01-24 22:59 UTC, wangding commented
commit ac384b5
I have fixed the name and version in package.json @denysdovhan

2017-01-25 01:41 UTC, lilizhiwei commented
I have reviewed all the commits, there is no problem. @denysdovhan

2017-01-25 03:01 UTC, wangding commented
thank you for your patient :smile:

2017-01-25 07:34 UTC, gaomengyao commented
I think there is no problem in these commits. @denysdovhan

2017-01-26 12:21 UTC, denysdovhan commented
@lilizhiwei @gaomengyao hmm, strange. Usually there are at least few mistakes in translation. Anyway, gonna merge that. PR is welcome, so if there would be mistakes anyone can fix them.

2017-01-26 12:24 UTC, merged

2017-01-26 12:26 UTC, denysdovhan commented
Published as `v1.3.0`!
Thank you @wangding for contributing!
Thanks to @lilizhiwei @gaomengyao for review!

2017-01-26 12:36 UTC, denysdovhan commented
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr">🇨🇳🇨🇳🇨🇳 how-to-markdown@1.3.0 is out with Chinese translation! 🇨🇳🇨🇳🇨🇳<br>Thanks to wangding (<a href="https://t.co/Df0Q3mXiSW">https://t.co/Df0Q3mXiSW</a>)! <a href="https://t.co/gO8OWUdJrr">pic.twitter.com/gO8OWUdJrr</a></p>&mdash; Denys Dovhan (@denysdovhan) <a href="https://twitter.com/denysdovhan/status/824596723859386368">January 26, 2017</a></blockquote>