Ukrainian translation
workshopper/how-to-markdown pull request #55
Opened 2017-03-30 11:43 UTC by kostyandrew

2017-03-30 13:13 UTC, denysdovhan commented
I've asked philologists from @LambdaBooks to make a review.

2017-03-30 19:11 UTC, Mariannach requested changes

2017-03-30 19:11 UTC, Mariannach commented on exercises/blockquotes/uk.md
> +Часом нам необхідно процитувати чиїсь слова. В цьому разі цитата є саме тим, що нам необхідно.
**Інколи** нам необхідно зацитувати чиїсь слова

2017-03-30 19:11 UTC, Mariannach commented on exercises/blockquotes/uk.md
> +Синтаксис цитати є простим:
Синтаксис цитати  **простий**

2017-03-30 19:11 UTC, Mariannach commented on exercises/blockquotes/uk.md
> +Як ви бачите, новий рядок не розвиває цитату. Щоб розділити декілька цитати просто додайте пустий рядок між ними.
декілька **цитат**

2017-03-30 19:11 UTC, Mariannach commented on exercises/blockquotes/uk.md
> +Ви можете також додавати в цитату Markdown, не тільки текст звичайний текст:
не тільки (!) звичайний текст:

2017-03-30 19:11 UTC, Mariannach commented on exercises/blockquotes/uk.md
> +    > **Markdown** is a _lightweight markup language_ with plain text formatting syntax designed so that it can be converted to **HTML** and many other formats.
це не потрібно перекласти?

2017-03-30 19:11 UTC, Mariannach commented on exercises/blockquotes/uk.md
> +І додайте автора в цитату в наступний рядок після цієї цитати.
**наступному рядку **

2017-03-30 19:11 UTC, Mariannach commented on exercises/blockquotes/uk.md
> +Коли ви закінчите, перевірте ваш рішення.
Перевірте ваш**Е** рішення, коли (!) закінчите.

2017-03-30 19:11 UTC, Mariannach commented on exercises/code/uk.md
> +Щоб позначити частину тексту як код необхідно просто обернути його в зворотні лапки ( ``` ` ```). Ось приклад:
Щоб позначити частину тексту як код,(!) необхідно просто обернути його в зворотні лапки

2017-03-30 19:11 UTC, Mariannach commented on exercises/code/uk.md
> +### Блок код
Блоки коду ..?

2017-03-30 19:11 UTC, Mariannach commented on exercises/code/uk.md
> +Блоки коду або огортяються лініями з трьома зворотними лапками ( ``` ``` ```), або виділені відступом в чотири пробіли.
Блоки коду (!) огорт**А**ються лініями з трьома зворотними лапками ( ``` ``` ```), або виділені відступом **ДОВЖИНОЮ** в чотири пробіли

2017-03-30 19:11 UTC, Mariannach commented on exercises/code/uk.md
> +Підсвічування синтаксису не є частиною специфікації Markdown. Тим не менш, багато додатків підтримують підсвічування синтаксису. Які мови підтримуються і як ці назви мови повинні бути написано буде в
**Мови, які** підтримуються і **правильність написасання назв** буде відрізнятися для різних додатків.

2017-03-30 19:11 UTC, Mariannach commented on exercises/code/uk.md
> +Додайте `Code` як заголовок першого рівня в ваш файл.
**У** ваш файл

2017-03-30 19:11 UTC, Mariannach commented on exercises/emphasis/uk.md
> +Легко відмітити частину тексту як _курсив_, **напівжирний**, _**комбінований**_ і ~~перекреслений~~. Є кілька способів зробити виділення в Markdown, і кожен з них є читабельним.
Легко **відзначити** частину тексту

Є кілька способів зробити виділення в Markdown(!) і кожен з них є читабельним.

2017-03-30 19:11 UTC, Mariannach commented on exercises/emphasis/uk.md
> +    ~~Закресль цю лінію.~~
**закреслити** або ж **закресли**

2017-03-30 19:11 UTC, Mariannach commented on exercises/emphasis/uk.md
> +**|>** ~~Закресль цю лінію.~~
**закреслити** або ж **закресли**

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/solution/uk.md
> +Ви закінчили цей воркшоп! Тепер ви знайомі з Markdown і знаєте як читати і писати Markdown документи.
знаєте,(!) як читати і писати Markdown документи

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/solution/uk.md
> +Що ви повинні робити далі? Просто напишіть деякі Markdown. Перепишіть `README`-файл вашого проекту в Markdown чи почніть писати повідомлення в свій блог в Markdown, що завгодно.
**У** свій блог в Markdown(!) що завгодно.

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/solution/uk.md
> +У всякому разі, знання Markdown дуже хороша навичка яка є корисна.
знання Markdown -(!) дуже хороша навичка,(!) яка вам **обов'язково стане в нагоді**

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/solution/uk.md
> +Дякуємо вам за використання цього воркшоп. Перевірте інші воркшопи на <http://nodeschool.io>.
воркшоп**У**

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +Якщо ви розробник, то ви напевно чули про **GitHub**. GitHub є важливою частиною спільноти. Чому ми говоримо про це? Це тому, що GitHub є великим клієнтом Markdown. Більш того, GitHub використовує св
` GitHub є важливою частиною спільноти ` - варто вказати якої спільноти

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +З попередніх вправ ви вже знайомі з підсвічуванням синтаксису в блоках коду і таблицями. Проте, є деякі інші функції які можуть бути корисні для вас.
Проте, є **Й** інші функції,(!) які можуть **стати** корисн**ими** для вас.

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +Для створення списку завдань ви повинні створити упорядкований або невпорядкований список. Потім ви можете використовувати квадратні дужки які будуть перетворені в поле для прапорці. `x` між дужками
Потім ви можете використовувати квадратні дужки,(!) які будуть перетворені в поле для прапорці.

 `x` між дужками **позначає** поле як завершене.

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +- [x] синтаксис списоку вимагається (невпорядкований або впорядкований список підтримується)
**СПИСКУ**

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +- [ ] це невиконаний пункт
**НЕ ВИКОНАНИЙ** пункт

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +    - [ ] це невиконаний пункт
**НЕ ВИКОНАНИЙ** пункт

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +### посилання SHA
**П**осилання

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +Згадка користовуча офрмлюється в форматі символ `@` разом з _ім'ям користувача_ відправить повідомлення користувачу, щоб він міг прийти і переглянути коментар. Це називається **@згадака** , тому що в
**користувача**

в **такому** форматі:(!) символ `@` разом з _ім'ям користувача_  -(!)відправить повідомлення користувачу


ви згадуєт**Е** **ОСОБУ**

2017-03-30 19:11 UTC, Mariannach commented on exercises/gfm/uk.md
> +Потім помітьте пункт `ho` як виконаний.
замість *помітьте* - **ПОЗНАЧТЕ**
БО
ПОМІЧАТИ, аю, аєш, недок., ПОМІТИТИ, ічу, ітиш, док., перех. і без додатка.
1. Сприймати зором; бачити.
2. Сприймати слухом; чути
3. Відчувати що-небудь....

2017-03-30 19:11 UTC, Mariannach commented on exercises/headings/solution/uk.md
> +У всіх наступних вправах ви повинні додати заголовки з ім'ям поточної вправи.
У всіх **ІНШИХ** вправах   - щоб уникнути тафтології

2017-03-30 19:11 UTC, Mariannach commented on exercises/headings/uk.md
> +Важливо класифікувати інформацію. Ось коли заголовки допомагають.
**Заголовки допомагають,(!) коли нам важливо класифікувати інформацію**

2017-03-30 19:11 UTC, Mariannach commented on exercises/hello_world/uk.md
> +**Markdown** - це легкий, легко читаємий, простий в написанні текстовий формат для укладання всіх форм написання по всьому Інтернету. Markdown дозволяє контролювати відображення документа: форматуван
це легкий, **читабельний**, простий в написанні текстовий формат

2017-03-30 19:11 UTC, Mariannach commented on exercises/hello_world/uk.md
> +Тут нема чітко визначеного стандарту. Markdown це просто загальні правила про те, як писати читається і форматований текст.
`як писати читається і форматований текст.` - щось тут не так

2017-03-30 19:11 UTC, Mariannach commented on exercises/hello_world/uk.md
> +Реалізації Markdown доступні для більш десятка мов програмування (_JavaScript_, _Ruby_, _Python_, _PHP_, _Perl_ та інші). Крім того, багато платформи і фреймворків підтримують Markdown з коробки. Нап
більш **ніж** десятка мов програмування 

багато **платформ**

2017-03-30 19:11 UTC, Mariannach commented on exercises/html/uk.md
> +Він не буде працювати.
Він не працювати**ме**.

2017-03-30 19:11 UTC, Mariannach commented on exercises/images/uk.md
> +Вкладення зображень дуже схоже на вставку посилань. Для того, щоб вставити зображення, яке ви повинні використовувати цей синтаксис:
щоб вставити зображення, (!) ви повинні використовувати цей синтаксис:

2017-03-30 19:11 UTC, Mariannach commented on exercises/images/uk.md
> +Як ви можете бачити, єдина відмінність полягає в тому, що ви повинні додати знак оклику перед тим квадратом дужки. `alt text` це альтернативний текст для зображення (аналогічно атрибуту `alt` в HTML)
**Як бачите**,  єдина відмінність ...

2017-03-30 19:11 UTC, Mariannach commented on exercises/links/solution/uk.md
> +Вказівники використовувати дуже зручно в тих випадках коли необхідно написати великий документ, наприклад, документацію для вашого проекту. Якщо у вас є багато посилань і ви хочете легко керувати ним
Вказівники використовувати дуже зручно в тих випадках,(!) коли необхідно написати .

то(!) можете створити розділ в нижній частині файлу і залишити всі (!)  вказівники там.  - надто багато **ВИ**

2017-03-30 19:11 UTC, Mariannach commented on exercises/links/solution/uk.md
> +Вище, `<!-- Мої вказівники -->` є HTML-коментарем який буде пропущено. Ви можете пропустити цей коментар, але насправді він допомагає показати розділ з посиланнями. Такий підхід допоможе вам відстежу
є HTML-коментарем,(!) який буде пропущено.

2017-03-30 19:11 UTC, Mariannach commented on exercises/links/uk.md
> +Вище `text` це текст посилання, `href` це ваша посилання на ресурс (схоже на `href` атрибут в HTML), `alt` iальтернативний текст для посилання (схоже на `alt` атрибут в HTML). Текст на засланні може
`text` -(!) це текст   ..`href` -(!) це ваша ... `alt` -  **альтернативний**

`Текст на засланні`  - це як Шевченко?))

2017-03-30 19:11 UTC, Mariannach commented on exercises/links/uk.md
> +    Якийсь текст, щоб показати що вказівки на посилання можуть слідувати пізніше:
Якийсь текст, щоб показати,(!) що вказівки на посилання

2017-03-30 19:11 UTC, Mariannach commented on exercises/links/uk.md
> +Будь ласка, скопіюйте цей текст в новий файл і помітте фразу **'how-to-markdown'** в якості посилання вказівного стилю з вказівкою на себе. Нижче в файлі, додайте відповідне посилання, яка буде посил
**ПОЗНАЧТЕ** фразу

2017-03-30 19:11 UTC, Mariannach commented on exercises/lists/solution/uk.md
> +Ви можете використовувати будь-який порядок чисел у ваших упорядкованих списках. Наприклад, це позначення працює добре:
**В**порядкованих списках

2017-03-30 19:11 UTC, Mariannach commented on exercises/lists/uk.md
> +У новому файлі додайте заголовок першого рівеня `Lists`.
**РІВНЯ**

2017-03-30 19:11 UTC, Mariannach commented on exercises/lists/uk.md
> +Спробуйте написати свій власний список. Будь ласка, створіть новий файл і створити невпорядкований список в ньому:
створіть новий файл і (!) невпорядкований список в ньому

2017-03-30 19:11 UTC, Mariannach commented on exercises/tables/solution/uk.md
> +Ви зробили чудову таблицю населення світу. Тепер ви розумієте які дивовижні таблиці в Markdown? Вони прості і читаємі, навіть в сирцях файлу.
**читабельний** напевно краще буде.
`сирцях файлу`  ??

2017-03-30 19:11 UTC, Mariannach commented on exercises/tables/solution/uk.md
> +У наступній вправі ми розглянемо на горизонтальні лінії в Markdown.
`на горизонтальні` може не горизонтальні?

2017-03-30 19:11 UTC, Mariannach commented on exercises/tables/uk.md
> +Таблиці не є частиною специфікації Markdown, але багато парсеров підтримують їх. Особливо **GFM**, який використовується на GitHub.
багато парсер**ів**

2017-03-30 19:11 UTC, Mariannach commented on exercises/tables/uk.md
> +* Там повинно бути щонайменше 3 тире, що відокремлюють кожну клітинку заголовка. Двокрапки для вирівнювання колонок рахувати як тире.
(!) повинно бути щонайменше 3 тире,

2017-03-31 15:44 UTC, merged

2017-03-31 15:44 UTC, denysdovhan commented
Thanks for contributing!
Published as `v1.5.0`!